name: bip39
description: Dart implementation of Bitcoin BIP39 Mnemonic code for generating deterministic keys
version: 1.0.3
homepage: https://github.com/true-will/bip39
author: true-will

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.1
  hex: ^0.1.2
  # crypto: ^2.1.5
dev_dependencies:
  test: ^1.15.7
